### ISSUE TITLE
Tools label / description too large

### ISSUE THREAD

**Issue by jra001k** [hmenager/workflow-is-cwl#1]
![screenshot_2018-07-17_06-26-42](https://user-images.githubusercontent.com/38982162/42796552-1095b280-898b-11e8-97c6-a50d7b015b3d.png)

"label" and "doc" attributes are too large to be displayed in the list (on the left).

Notes:

* With galaxy tools XML descriptor, the text displayed is made of "name" and "description" attributes.
* With tools CWL descriptor, the text displayed is made of "label" and "doc" attributes.
* The mapping between those attributes take place in lib/galaxy/tools/cwl/parser.py (line 284)

**Comment by mscheremetjew** [comment]
I agree. This needs reviewing. I've noticed the same last time I visualised the whole workflow using cwlviewer.

**Comment by jra001k** [comment]
Temporary fix by extracting shortname from the label (substring before the colon mark).

https://github.com/hmenager/galaxy/commit/ad2f92b6e7d8922db71d1f6d3e47d873dbed6c75

https://github.com/hmenager/workflow-is-cwl/commit/8096119c65986b8c1c9d8f6a5fd136c0e52e6120
