### ISSUE TITLE
cwltool - InterProScan

### ISSUE THREAD

**Issue by jra001k** [hmenager/workflow-is-cwl#6]
```
$ cd workflow-is-cwl/tools/InterProScan
$ cwl-runner InterProScan-v5.cwl --proteinFile test_single_protein.fasta
'interproscan.sh' not found
[job InterProScan-v5.cwl] completed permanentFail
{}
Final process status is permanentFail
```

**Comment by mscheremetjew** [comment]
InterProScan isn't properly containerised yet. That due to the size of the image. As it is an inhouse software tool we are working towards a solution. But this might take some time.

**Comment by jra001k** [comment]
Documentation on how to install InterProScan 5 can be found her:

https://github.com/ebi-pf-team/interproscan/wiki/HowToDownload

Ignore the sections about 'Installing Panther Models' and 'Using the Local Pre-calculated Match Lookup Service (Optional)'.

**Comment by jra001k** [comment]
$ pip show cwltool
Name: cwltool
Version: 1.0.20180508202931

$ cd my_interproscan/interproscan-5.30-69.0
$ export PATH="$(pwd):$PATH

$ cd workflow-is-cwl/tools/InterProScan
$ cwl-runner --no-container InterProScan-v5.cwl --proteinFile test-input/test_single_protein.fasta
Final process status is success
```
Job outputs moved to "workflow-is-cwl/tools/InterProScan/expected_output" folder.
